### ISSUE TITLE
Add Kotlin Coroutine Support

### ISSUE THREAD

**Issue by cgm-aw** [reactiverse/reactiverse-contextual-logging#106]
Hi there,

I'm using this project for contextual logging and it works fine in most cases, however my stack is based on Kotlin and Coroutines.
Most of the time the context data is correct, but there are cases where the data gets mixed up with other context data.
I did not yet succeed in building a reproducer since it only seems to happen in complex call chains under some load.
However I assume a fix would be by using Kotlins [CoroutineContext](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.coroutines/-coroutine-context/) instead of Vertx' ContextInternal as described for [Open Tracing](https://vertx.io/docs/vertx-opentracing/java/#_coroutines_support). 

Are there plans to support coroutines? 

Best regards

**Comment by tsegismont** [comment]
There are no plans to implement a contextual data storage with the specific Kotlin coroutine context.

If you manage to put together a small reproducer, I'd be glad to look into it.
