### ISSUE TITLE
Evaluate integration options with distributed tracing

### ISSUE THREAD

**Issue by tsegismont** [reactiverse/reactiverse-contextual-logging#2]
Could be some documentation only.

Would be nice to have, for example, trace/span ids in `ContextualData`.

**Comment by tsegismont** [comment]
Zipkin integration with slf4j MDC

**Comment by thced** [comment]
@tsegismont Any progress?
I am actually fiddling with logback/logstash/json and any hints would be highly appreciated!

**Comment by tsegismont** [comment]
Not yet

**Comment by tsegismont** [comment]
Won't fix, check out tracing libraries integration with logging, like this one:

https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/logback/logback-mdc-1.0/library
