### ISSUE TITLE
Incomplete messages 

### ISSUE THREAD

**Issue by edgar2701** [reactiverse/reactiverse-contextual-logging#3]
Hello, I am trying to make a implementation with reactiverse to receive logs in Graylog, when placing the logstash Encoder the message is clipped, randomly, (I send screen)
![image](https://user-images.githubusercontent.com/78026210/109216557-0e5bf880-778b-11eb-93d5-fca1d40219ca.png)

Removing the conversionRule from the XML does not cut the message, but I lose the information from the contextualData but it does not cut the message (I send screen again)
![image](https://user-images.githubusercontent.com/78026210/109216983-9cd07a00-778b-11eb-8da1-02f1ebc2e983.png)

It is likely that I am doing something improper, but doing local tests everything seems to work correctly, I send an example of the XML to know if I am missing something, I appreciate any help you can offer me.

`<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <conversionRule conversionWord="vcl" converterClass="io.reactiverse.contextual.logging.LogbackConverter"/>
        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
            <encoder class="net.logstash.logback.encoder.LogstashEncoder">
                <provider class="net.logstash.logback.composite.loggingevent.LoggingEventPatternJsonProvider">
                    <pattern>{"message":"[%thread] %-4level - TraceId = %vcl{TraceId:-foobar} - ClientId = %vcl{ClientId:-foobar} - %msg"}</pattern>
                </provider>
            </encoder>
        </appender>
    <logger name="com.test" level="debug"/>
    <root level="warn">
        <appender-ref ref="STDOUT"/>
    </root>
</configuration>`

**Comment by tsegismont** [comment]
It looks like Graylog is configured to parse the log message and is confused when the info is present.
