### ISSUE TITLE
JBoss logging support?

### ISSUE THREAD

**Issue by aluedtke7** [reactiverse/reactiverse-contextual-logging#41]
Hi, I would like to use the contextual logging in a Quarkus project. Unfortunately, Quarkus is using JBoss logging and I didn't find a way to use the `%vcl{requestId}`.

Do you see a chance to support JBoss logging?

**Comment by tsegismont** [comment]
@aluedtke7 as a workaround, can you try to use the [log4j API](https://quarkus.io/guides/logging#what-about-apache-log4j) with the [context data provider](https://reactiverse.io/reactiverse-contextual-logging/#log4j2_context_data_provider)

@jamezp is there a way to provide JBoss Logging LogManager with contextual data when an event is created? I'm not familiar with the JBoss Logging implementation but if that's possible, we could add support for it here.

**Comment by aluedtke7** [comment]
We used already the MDC way of handling context infos, but this doesn't work right in Vert.x. That's why we tried this project.
We want to pass a Request ID around.
The pattern options are obviously the same for Quarkus ;-)

**Comment by jamezp** [comment]
I _think_ there may have been some changes in Quarkus to propagate `MDC` contexts. @dmlloyd is that a thing yet?

That said, MDC by default is a `ThreadLocal` so the contexts are not propagated to other threads without explicitly doing so.

**Comment by dmlloyd** [comment]
The changes are in Quarkus but I don't think they're wired up to context propagation yet.

**Comment by tsegismont** [comment]
@aluedtke7 can you try this as a workaround? https://stackoverflow.com/a/70892802/2133695

**Comment by aluedtke7** [comment]
I will try that.

**Comment by luneo7** [comment]
Something like a Quarkus counterpart of this lib is being done in https://github.com/quarkusio/quarkus/pull/25311
