### ISSUE TITLE
Using ContextualLogging with GELF

### ISSUE THREAD

**Issue by Podnevar** [reactiverse/reactiverse-contextual-logging#49]
I'm trying to use contextual logging with Graylog (GELF). The problem i'm having and can't figure it out is how to send this additional fields that I added to context logs. Logging works ok, I see logs on Graylog just no additional fields like it showed with MDC.

What I tried is to use custom ContextDataProvider with creating file under META-INF/services org.apache.logging.log4j.core.util.ContextDataProvider and inserting then io.reactiverse.contextual.logging.VertxContextDataProvider

My log4j2.xml:
`<Configuration>
    <Appenders>
        <Socket name="GELF" protocol="tcp" host="my.url" port="9850">
            <GelfLayout includeStackTrace="true" includeThreadContext="true" includeNullDelimiter="true"
                        compressionType="OFF">
            </GelfLayout>
        </Socket>
    </Appenders>
        <Loggers>
        <Root level="INFO">
            <AppenderRef ref="GELF" />
        </Root>
    </Loggers>
</Configuration>`

How much I tried to debug it seems log4j doesen't pickup this VertxContextDataProvider, could I miss something when creating this file? Is type wrong or what it could be?

**Comment by tsegismont** [comment]
Can you share a small reproducer project please?

**Comment by Podnevar** [comment]
> Can you share a small reproducer project please?

Here is the recreation of the problem:
https://github.com/Podnevar/contextual-logging-log4j-reactive
